export const BOX_SHADOW = {
    ON_CHANGE_SLIDER: 'ON_cHANGE_SLIDER_BOX_SHADOW',
    ON_CHANGE_INSET: 'ON_CHANGE_INSET_BOX_SHADOW',
    ON_CHANGE_COLOR: 'ON_CHANGE_COLOR_BOX_SHADOW',
    ON_ADD_LAYER: 'ON_ADD_LAYER_BOX_SHADOW'
}